name: check
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 1.0

learning_rate: 0.0001 
batch_size: 6
num_threads: 12

resume: False
overfit: True

momentum: 0.5 
optim: Adam

num_epoch: 15
freq_eval: 10
freq_plot: 10
freq_show: 10
freq_save: 500
schedule: [5, 10]