name: virgin
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05

learning_rate: 0.0001 
batch_size: 12
num_threads: 24

# ckpt_path: ../data/checkpoints/overfit/ckpt_0.pth
resume: False
overfit: False

momentum: 0.5 
optim: Adam

num_epoch: 15
freq_eval: 1000
freq_plot: 10
freq_show: 200
freq_save: 500
schedule: [5, 10]