name: virgin_light
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 0.5

learning_rate: 1e-3
batch_size: 24
num_threads: 24

# ckpt_path: ../data/checkpoints/virgin_light/top_k_epoch=1.ckpt
# resume: True
overfit: False

momentum: 0.5 
optim: Adam

num_epoch: 15
freq_eval: 1000
freq_plot: 10
freq_show: 200
freq_save: 500
schedule: [4, 7, 13]