name: overfit
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 0.5

learning_rate: 0.0001 
batch_size: 2
num_threads: 2

# ckpt_path: ../data/checkpoints/virgin/ckpt_0.pth
# resume: True
overfit: True

momentum: 0.5 
optim: Adam

num_epoch: 15
freq_plot: 100
freq_show: 100
schedule: [5, 10]