name: NASA_w_sk_3
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 3.0
  train_bsize: 1.0
  val_bsize: 0.2
  test_bsize: 1.0

learning_rate: 1e-4
batch_size: 6
num_threads: 6
gpus: [0]

ckpt_path: ""
overfit: 0
resume: False
test_mode: False
fast_dev: False

momentum: 0.5 
optim: Adam

num_epoch: 10
freq_eval: 4000
freq_plot: 400
freq_show: 800
freq_save: 2000
schedule: [4, 7]